name: Deploy
on:
  push:
    branches:
      - "*"
jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "17.1"
          cache: "npm"
          cache-dependency-path: app/package-lock.json
      - run: npm install
        working-directory: app
      - run: npm run build --if-present
        working-directory: app

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: SetupNode
        uses: actions/setup-node@v2
        with:
          node-version: "17.1"
          cache: "npm"
          cache-dependency-path: app/package-lock.json
      - name: Prettier
        run: npx prettier --check
        working-directory: app

  golint:
    name: Lint Go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: go-backend
